return {}
-- return {
--   {
--     "mfussenegger/nvim-dap",
--   },
--   {
--     "rcarriga/nvim-dap-ui",
--     dependencies = {
--       "mfussenegger/nvim-dap",
--     },
--     config = function()
--       local dap = require("dap")
--       local dapui = require("dapui")
--
--       dapui.setup()
--
--       -- Automatically open UI when debugging starts
--       dap.listeners.after.event_initialized["dapui_config"] = function()
--         dapui.open()
--       end
--       dap.listeners.before.event_terminated["dapui_config"] = function()
--         dapui.close()
--       end
--       dap.listeners.before.event_exited["dapui_config"] = function()
--         dapui.close()
--       end
--     end,
--   },
--   {
--     "microsoft/vscode-js-debug",
--     build = "npm install --legacy-peer-deps && git checkout package-lock.json && npx gulp vsDebugServerBundle && mv dist out",
--   },
--   {
--     "mxsdev/nvim-dap-vscode-js",
--     dependencies = {
--       "mfussenegger/nvim-dap",
--     },
--     config = function()
--       require("dap-vscode-js").setup({
--         debugger_path = vim.fn.stdpath("data") .. "/lazy/vscode-js-debug",
--         adapters = { "pwa-node", "pwa-chrome", "pwa-msedge", "node-terminal", "pwa-extensionHost" },
--       })
--
--       for _, language in ipairs({ "typescript", "javascript", "typescriptreact", "javascriptreact" }) do
--         require("dap").configurations[language] = {
--           {
--             type = "pwa-node",
--             request = "launch",
--             name = "Launch file",
--             program = "${file}",
--             cwd = "${workspaceFolder}",
--           },
--           {
--             type = "pwa-node",
--             request = "attach",
--             name = "Attach",
--             processId = require("dap.utils").pick_process,
--             cwd = "${workspaceFolder}",
--           },
--           {
--             type = "pwa-chrome",
--             request = "launch",
--             name = 'Start Chrome with "localhost"',
--             url = "http://localhost:3000",
--             webRoot = "${workspaceFolder}",
--             userDataDir = "${workspaceFolder}/.vscode/vscode-chrome-debug-userdatadir",
--           },
--         }
--       end
--     end,
--   },
-- }
